site_name: Fiori Apps' Usage
nav:
    - Overview: FPS01/main.md
    - Installation: FPS01/inst.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
plugins:
  - macros
  - search
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
extra:
  prod:
    fau:
      name: 'Fiori Apps Usage'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ''
      compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS02/main/'
      compatibleAsisMainLink: 'https://help.fioritracker.org/V2020/asis/FPS01/main/'
      compatibleAsisCenLink: 'https://help.fioritracker.org/V2020/asis/FPS01/inst-cen/'
      compatibleAsisManLink: 'https://help.fioritracker.org/V2020/asis/FPS01/inst-man/'
  